#!/usr/bin/env python3
"""Convert Shot Designer's FXG vector assets into a JS module of SVG snippets."""
import os, re, json, xml.etree.ElementTree as ET

FXG_DIR = "/Applications/Shot Designer.app/Contents/Resources/FXG"
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "assets.js")
NS = "{http://ns.adobe.com/fxg/2008}"

def tag(e):
    return e.tag.split("}")[-1] if "}" in e.tag else e.tag

def num(e, k, d=0.0):
    v = e.get(k)
    try: return float(v)
    except (TypeError, ValueError): return d

def paint(el):
    """Return (fill, stroke, stroke-width) for a shape element."""
    fill, stroke, sw = "none", "none", None
    for child in el:
        t = tag(child)
        if t == "fill":
            for c in child:
                if tag(c) == "SolidColor":
                    fill = c.get("color", "#000000")
        elif t == "stroke":
            for c in child:
                if tag(c) == "SolidColorStroke":
                    stroke = c.get("color", "#000000")
                    sw = c.get("weight", "1")
    return fill, stroke, sw

def shape(el, dx, dy):
    t = tag(el)
    fill, stroke, sw = paint(el)
    a = f'fill="{fill}" stroke="{stroke}"'
    if sw: a += f' stroke-width="{sw}"'
    a += ' stroke-linejoin="round" stroke-linecap="round"'
    x, y = num(el, "x") + dx, num(el, "y") + dy
    if t == "Path":
        d = el.get("data", "")
        w = el.get("winding")
        rule = ' fill-rule="evenodd"' if w == "evenOdd" else ""
        # Path x/y act as a translation of the path data
        tr = f' transform="translate({x:g},{y:g})"' if (x or y) else ""
        return f'<path d="{d}"{rule}{tr} {a}/>'
    if t == "Rect":
        w, h = num(el, "width"), num(el, "height")
        rx = el.get("radiusX")
        r = f' rx="{rx}"' if rx else ""
        return f'<rect x="{x:g}" y="{y:g}" width="{w:g}" height="{h:g}"{r} {a}/>'
    if t == "Ellipse":
        w, h = num(el, "width"), num(el, "height")
        return (f'<ellipse cx="{x + w / 2:g}" cy="{y + h / 2:g}" '
                f'rx="{w / 2:g}" ry="{h / 2:g}" {a}/>')
    if t == "Line":
        return (f'<line x1="{num(el,"xFrom")+x:g}" y1="{num(el,"yFrom")+y:g}" '
                f'x2="{num(el,"xTo")+x:g}" y2="{num(el,"yTo")+y:g}" {a}/>')
    return None

def walk(el, dx=0.0, dy=0.0, out=None):
    out = [] if out is None else out
    for child in el:
        t = tag(child)
        if t == "Private" or child.tag.startswith("{http://ns.adobe.com/ai"):
            continue
        if t == "Group":
            walk(child, dx + num(child, "x"), dy + num(child, "y"), out)
        else:
            s = shape(child, dx, dy)
            if s: out.append(s)
    return out

def bbox(parts):
    """Rough bounds from all numeric coordinates, good enough for centering."""
    xs, ys = [], []
    for p in parts:
        for m in re.finditer(r'(?:cx|x1|x2|x)="(-?[\d.]+)"', p): xs.append(float(m.group(1)))
        for m in re.finditer(r'(?:cy|y1|y2|y)="(-?[\d.]+)"', p): ys.append(float(m.group(1)))
    return (min(xs), min(ys), max(xs), max(ys)) if xs and ys else (0, 0, 0, 0)

def main():
    assets = {}
    for fn in sorted(os.listdir(FXG_DIR)):
        if not fn.endswith(".fxg"):
            continue
        name = fn[:-4]
        root = ET.parse(os.path.join(FXG_DIR, fn)).getroot()
        parts = walk(root)
        if not parts:
            print("  (empty)", name)
            continue
        assets[name] = {
            "svg": "".join(parts),
            "vw": num(root, "viewWidth", 800.0),
            "vh": num(root, "viewHeight", 600.0),
        }
    with open(OUT, "w") as f:
        f.write("// Generated by tools/fxg2svg.py from Shot Designer's FXG assets.\n")
        f.write("// Vector art (c) Hollywood Camera Work; converted for local use.\n")
        f.write("export const FXG = " + json.dumps(assets, indent=1) + ";\n")
    print(f"wrote {len(assets)} assets -> {OUT}")

main()
